#!/usr/bin/env bash
# installs nginx and says hello
sudo apt-get -y update
sudo apt-get -y install nginx
sudo /etc/init.d/nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html

sed -i '50 i rewrite ^/redirect_me/$ 301 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
