#!/usr/bin/env bash
# installs nginx and says hello
sudo apt-get -y update
sudo apt-get -y install nginx
sudo /etc/init.d/nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html;

echo "
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	error_page 404 /error404.html;

	location / {

		try_files \$uri \$uri/ =404;
}" | sudo tee /etc/nginx/sites-available/default

sed -i '5 i rewrite ^/redirect_me/$ 301 permanent;' /etc/nginx/sites-available/default


sudo service nginx restart
