#!/usr/bin/env bash
# configures a new ubuntu machine
sudo apt update
sudo apt upgrade -y
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo apt install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6 -y
sudo apt update$ sudo apt install haproxy -y
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg-org
config="frontend front_smtp
        bind *:25
        mode tcp
        default_backend back_smtp

backend back_smtp
        mode tcp
        balance roundrobin
        server smtp1 192.168.1.10:25 check
        server smtp2 192.168.1.20:25 check"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
