#!/usr/bin/env bash
# This script loops with while and if elif else

x=1
while [ $x -lt 11 ]
do
	if [ $x -eq 4 ]
	then
		echo "bad luck"
	elif [ $x -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( x++ ))
done
