#!/usr/bin/env bash
# This resolves localhost and facebook


if [ $(grep -c "127.0.0.1" /etc/hosts) -eq 0 ]
then
	echo "127.0.0.2	localhost" > /etc/hosts
	echo "8.8.8.8 facebook.com" >> /etc/hosts
fi
